services:
    telegram-bot:
      build:
        context: ..
        dockerfile: .docker/Dockerfile
        # target: runtime
      command: ["python3", "src/main.py"]
      restart: unless-stopped
      env_file:
        - .env

    vk-bot:
      build:
        context: ..
        dockerfile: .docker/Dockerfile
        # target: runtime
      command: ["python3", "src/vk_bot.py"]
      restart: unless-stopped
      env_file:
        - .env

      