services:
  telegram-bot:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    command: [ "python3", "src/telegram/entry.py" ]
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - proxy

  vk-bot:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    command: [ "python3", "src/vk/entry.py" ]
    restart: unless-stopped
    env_file:
      - .env
  proxy:
    build:
      context: ../src/proxy
      dockerfile: ../../.docker/DockerfileProxy
      target: prod
      args:
        PROXY_CONNECTION_LINK: ${PROXY_CONNECTION_LINK}
        PROXY_PORT: ${PROXY_PORT}
        PROXY_CONFIG_PATH: ${PROXY_CONFIG_PATH}
    env_file:
      - .env
    expose:
      - "${PROXY_PORT}"
    
